//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzeria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Items
    {
        public int item_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> pizza_id { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Pizzas Pizzas { get; set; }
    }
}
